# Generated by Django 3.0.5 on 2020-05-11 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, default='', upload_to='', verbose_name='Cover image'),
        ),
    ]
