# Generated by Django 3.0.5 on 2020-05-16 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20200516_1114'),
        ('reviews', '0003_auto_20200516_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='books.Book', verbose_name='Book'),
            preserve_default=False,
        ),
    ]
